name: task_tracker_mobile_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  intl: ^0.18.1
  another_flushbar: ^1.10.28
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
    android: true
    image_path: "assets/taskTrackerAppLogo.png"


flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:




  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
     - assets/




